security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: user
      accessTokenUri: http://piggymetrics-authentication-service.mybluemix.net/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 169.46.154.152
      username: user
      password: user
      database: piggymetrics
      port: 26000

server:
  context-path: /accounts
 # port: 6000
