logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://piggymetrics-registry-service.mybluemix.net/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://piggymetrics-auth-service.mybluemix.net/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq
