security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: user
      accessTokenUri: http://piggymetrics-authentication-service.mybluemix.net/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 169.46.154.152
      username: user
      password: user
      database: piggymetrics
      port: 27000

server:
  context-path: /statistics
 # port: 7000

rates:
  url: http://api.fixer.io
